<?php

require 'tripal_manage_menus.install';

/**
 * Implements hook_entity_delete().
 */
function tripal_manage_menus_entity_delete($entity, $type) {
  if (in_array($entity->term_id, get_entity_bundle('organism')))
    rebuild_menu_links('main-menu', 'Trees', 'organism');
}

/**
 * Implements hook_entity_insert().
 */
function tripal_manage_menus_entity_insert($entity, $type) {
  if (in_array($entity->term_id, get_entity_bundle('organism')))
    rebuild_menu_links('main-menu', 'Trees', 'organism');
}

/**
 * Implements hook_entity_update().
 */
function tripal_manage_menus_entity_update($entity, $type) {
  if (in_array($entity->term_id, get_entity_bundle('organism'))) {
    rebuild_menu_links('main-menu', 'Trees', 'organism');
  }
}

/**
 * Removes all existing menu links for a given parent menu link and rebuilds the links from scratch.
 *
 * @param $menu_name
 *  A string for the name of the menu containing the link to rebuild.
 *
 * @param $link_title
 *  A string for the name of the link to rebuild.
 *
 * @param $bundle_name
 *  A string of the name of the bundle containing the entities for which the links will be created.
 *
 */
function rebuild_menu_links($menu_name, $link_title, $bundle_name)
{
  $mlid = get_menu_link($menu_name, $link_title);
  $bundle_id = get_entity_bundle($bundle_name);
  $entities = get_entities($bundle_id);

  remove_menu_links($menu_name, $mlid);
  update_menu_links($entities, $menu_name, $mlid);
}